bookstore/authors/urls.py
# from django.urls import path
# from django.conf.urls.static import static

# from bookstore import settings
# from . import views

# app_name = 'authors'

# # urlpatterns = [
# #     path("", views.authors, name="authors"),
# #     path("createauthor", views.createauthor, name="createauthor"),
# # ]


# urlpatterns = [
#     path("", views.authors, name="authors"),
#     path("create/", views.createauthor, name="createauthor"),
#     path("<int:id>/edit/", views.editauthor, name="editauthor"),
#     path("<int:id>/delete/", views.deleteauthor, name="deleteauthor"),
# ]


from django.urls import path
from authors.views import (
    AuthorListView,
    AuthorCreateView,
    AuthorUpdateView,
    AuthorDeleteView,
)

app_name = "authors"

urlpatterns = [
    path("", AuthorListView.as_view(), name="authors"),
    path("create/", AuthorCreateView.as_view(), name="createauthor"),
    path("edit/<int:pk>/", AuthorUpdateView.as_view(), name="editauthor"),
    path("delete/<int:pk>/", AuthorDeleteView.as_view(), name="deleteauthor"),
    
]

bookstore/books/urls.py
# from django.urls import include, path
# from django.conf.urls.static import static
# from authors.views import authors

# from bookstore import settings
# from . import views

# from django.urls import path
# from books.views import BookListView, BookCreateView, BookUpdateView, BookDeleteView

# urlpatterns = [
#     path("home/", views.home, name="home"),
#     path("contactus/", views.contactus, name="contactus"),
#     path("authors/", include("authors.urls", namespace="authors")),
#     path("aboutus/", views.aboutus, name="aboutus"),
#     path("<int:id>/bookdetail", views.bookdetail, name="bookdetail"),
#     path("<int:id>/bookdelete", views.bookdelete, name="bookdelete"),
#     path("createbook/", views.createbook, name="createbook"),
#     path("<int:id>/editbook", views.edit, name="editbook"),
#     # path("authors/", views.authors, name="authors"),
# ]
# from django.urls import path

# from authors import views
# from .views import (
#     BookListView,
#     BookDetailView,
#     BookCreateView,
#     BookUpdateView,
#     BookDeleteView,
# )

# urlpatterns = [
#     # other URL patterns
#     path("", BookListView.as_view(), name="home"),
#     path("book/<int:pk>/", BookDetailView.as_view(), name="bookdetail"),
#     path("book/create/", BookCreateView.as_view(), name="createbook"),
#     path("book/<int:pk>/edit/", BookUpdateView.as_view(), name="editbook"),
#     path("book/<int:pk>/delete/", BookDeleteView.as_view(), name="deletebook"),

# ]
# books/urls.py

from django.urls import path
from .views import (
    BookListView,
    BookDetailView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
)

app_name = "books"

urlpatterns = [
    path("", BookListView.as_view(), name="home"),
    path("book/<int:pk>/", BookDetailView.as_view(), name="bookdetail"),
    path("book/create/", BookCreateView.as_view(), name="createbook"),
    path("book/<int:pk>/edit/", BookUpdateView.as_view(), name="editbook"),
    path("book/<int:pk>/delete/", BookDeleteView.as_view(), name="deletebook"),
]

bookstore/bookstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path("admin/", admin.site.urls),
    path("books/", include(("books.urls", "books"), namespace="books")),
    path("authors/", include("authors.urls")),
    # path("authors/", include("authors.urls", namespace="authors")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/authors/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to="authors/images/", null=True, blank=True)
    bdate = models.DateField(null=True, blank=True, default="1990-01-01")
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.name

    # @property
    # def show_url(self):
    #     url = reverse("authors", args=[self.id])
    #     return url

bookstore/authors/forms.py
from django import forms
from .models import Author


        
class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

bookstore/authors/views.py
# # authors/views.py
# from django.shortcuts import get_object_or_404, redirect, render
# from authors.forms import AuthorForm
# from authors.models import Author


# def authors(request):
#     authors = Author.objects.prefetch_related("books").all()
#     return render(request, "authors/authors.html", {"authors": authors})


# def createauthor(request):
#     if request.method == "POST":
#         form = AuthorForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect("authors:authors")
#     else:
#         form = AuthorForm()
#     return render(request, "authors/createauthor.html", {"form": form})


# def editauthor(request, id):
#     author = get_object_or_404(Author, id=id)
#     if request.method == "POST":
#         form = AuthorForm(request.POST, request.FILES, instance=author)
#         if form.is_valid():
#             form.save()
#             return redirect("authors:authors")
#     else:
#         form = AuthorForm(instance=author)
#     return render(request, "authors/editauthor.html", {"form": form, "author": author})

# def deleteauthor(request, id):
#     author = get_object_or_404(Author, id=id)
#     author.delete()
#     return redirect("authors:authors")




from django.urls import reverse_lazy
from authors.forms import AuthorForm
from authors.models import Author
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView


class AuthorListView(ListView):
    model = Author
    template_name = "authors/authors.html"
    context_object_name = "authors"


class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorForm
    template_name = "authors/createauthor.html"
    success_url = "/authors/"


class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AuthorForm
    template_name = "authors/editauthor.html"
    success_url = "/authors/"


class AuthorDeleteView(DeleteView):
    model = Author
    template_name = "authors/deleteauthor.html"
    success_url = reverse_lazy("authors:authors")

bookstore/authors/templates/authors/authors.html
{% extends "layouts/base.html" %}

{% load static %}

{% block title %}Authors{% endblock %}

{% block content %}
    <div class="container">
        <a href="{% url 'authors:createauthor' %}" class="btn btn-secondary mt-3">Add Author</a>
        <a href="{% url 'books:home' %}" class="btn btn-secondary mt-3">Back to List</a>

        <h1 class="my-4">Authors</h1>
        <div class="row">
        {% for author in authors %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <img src="{{ author.image.url }}" class="card-img-top" alt="{{ author.name }}" width="200" height="300">
                        <div class="card-body">
                            <h5 class="card-title">{{ author.name }}</h5>
                            <p class="card-text">Birth Date: {{ author.bdate }}</p>
                            <p>Books:</p>
                            <ul>
                                {% for book in author.books.all %}
                                    <li>{{ book.name }}</li>
                                {% endfor %}
                            </ul>
                            <a href="{% url 'authors:editauthor' author.id %}" class="btn btn-primary">Edit Author</a>
                            <a href="{% url 'authors:deleteauthor' author.id %}" class="btn btn-danger">Delete Author</a>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

bookstore/authors/templates/authors/createauthor.html
{% extends "layouts/base.html" %}

{% load static %}

{% block title %}Create Author{% endblock %}

{% block content %}
<div class="container">
    <h2 class="my-4">Create Author</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Enter author's name">
        </div>

        <div class="mb-3">
            <label for="bdate">Birth Date</label>
            <input type="date" name="bdate" class="form-control" id="bdate">
        </div>

        <div class="mb-3">
            <label for="image">Image</label>
            <input type="file" name="image" class="form-control" id="image">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

bookstore/authors/templates/authors/deleteauthor.html
{% extends "layouts/base.html" %}

{% block title %}Delete Author{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Are you sure you want to delete "{{ object.name }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm Delete</button>
        <a href="{% url 'authors:authors' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

bookstore/authors/templates/authors/editauthor.html
{% extends "layouts/base.html" %}


{% block title %} Edit author {% endblock %}

{% block content %}
<div class="container">
    <h2 class="my-4">Edit Author</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name">Name</label>
            <input type="text" name="name" value="{{author.name}}" class="form-control" id="name" placeholder="Enter author's name">
        </div>

        <div class="mb-3">
            <label for="bdate">Birth Date</label>
            <input type="date" name="bdate" value="{{author.bdate}}" class="form-control" id="bdate">
        </div>

        <div class="mb-3">
            <label for="image">Image</label>
            <input type="file" name="image" value="{{author.image}}" class="form-control" id="image">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}