bookstore/books/urls.py
# from django.urls import include, path
# from django.conf.urls.static import static
# from authors.views import authors

# from bookstore import settings
# from . import views

# from django.urls import path
# from books.views import BookListView, BookCreateView, BookUpdateView, BookDeleteView

# urlpatterns = [
#     path("home/", views.home, name="home"),
#     path("contactus/", views.contactus, name="contactus"),
#     path("authors/", include("authors.urls", namespace="authors")),
#     path("aboutus/", views.aboutus, name="aboutus"),
#     path("<int:id>/bookdetail", views.bookdetail, name="bookdetail"),
#     path("<int:id>/bookdelete", views.bookdelete, name="bookdelete"),
#     path("createbook/", views.createbook, name="createbook"),
#     path("<int:id>/editbook", views.edit, name="editbook"),
#     # path("authors/", views.authors, name="authors"),
# ]
# from django.urls import path

# from authors import views
# from .views import (
#     BookListView,
#     BookDetailView,
#     BookCreateView,
#     BookUpdateView,
#     BookDeleteView,
# )

# urlpatterns = [
#     # other URL patterns
#     path("", BookListView.as_view(), name="home"),
#     path("book/<int:pk>/", BookDetailView.as_view(), name="bookdetail"),
#     path("book/create/", BookCreateView.as_view(), name="createbook"),
#     path("book/<int:pk>/edit/", BookUpdateView.as_view(), name="editbook"),
#     path("book/<int:pk>/delete/", BookDeleteView.as_view(), name="deletebook"),

# ]
# books/urls.py

from django.urls import path
from .views import (
    BookListView,
    BookDetailView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
)

app_name = "books"

urlpatterns = [
    path("", BookListView.as_view(), name="home"),
    path("book/<int:pk>/", BookDetailView.as_view(), name="bookdetail"),
    path("book/create/", BookCreateView.as_view(), name="createbook"),
    path("book/<int:pk>/edit/", BookUpdateView.as_view(), name="editbook"),
    path("book/<int:pk>/delete/", BookDeleteView.as_view(), name="deletebook"),
]

bookstore/bookstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path("admin/", admin.site.urls),
    path("books/", include(("books.urls", "books"), namespace="books")),
    path("authors/", include("authors.urls")),
    # path("authors/", include("authors.urls", namespace="authors")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/books/models.py
from django.db import models
import authors
from django.shortcuts import reverse
from authors.models import Author

# Create your models here.


class Book(models.Model):
    name = models.CharField(max_length=100)
    pages = models.IntegerField()

    author = models.ForeignKey    (
        Author,
        on_delete=models.CASCADE,
        related_name="books",
        null=True,
        blank=True
    )
    price = models.IntegerField()

    cover = models.ImageField(upload_to='books/images/', blank=True, null=True)
    def __str__(self):
        return self.name

    @property
    def image_url (self):
        return f'/media/{self.cover}'
    @property
    def show_url (self):
        url = reverse('bookdetail', args=[self.id])
        return url

    @property
    def edit_url(self):
        url = reverse("editbook", args=[self.id])
        return url

bookstore/books/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["name", "pages", "price", "author", "cover"]

bookstore/books/views.py
# from django.shortcuts import render, get_object_or_404, redirect

# from authors.models import Author
# from .models import Book


# def home(request):
#     booklist = Book.objects.all()
#     return render(request, "books/home.html", {"booklist": booklist})


# def contactus(request):
#     return render(request, "books/contactus.html")


# def aboutus(request):
#     return render(request, "books/aboutus.html")


# def bookdetail(request, id):
#     book = get_object_or_404(Book, id=id)
#     return render(request, "books/bookdetail.html", {"book": book})


# def bookdelete(request, id):
#     book = get_object_or_404(Book, id=id)
#     book.delete()
#     return redirect("home")


# def createbook(request):
#     if request.method == "POST":

#         name = request.POST.get("name")
#         no_pages = request.POST.get("pages")
#         price = request.POST.get("price")
#         cover = request.FILES.get("cover")
#         author_id = request.POST.get("author")


#         author = Author.objects.get(id=author_id)

#         book = Book.objects.create(
#             name=name, no_pages=no_pages, cover= cover, price=price, author=author
#         )
#         return redirect(book.show_url)
#     else:
#         authors = Author.objects.all()
#         context = {'authors': authors}
#         return render(request, "books/createbook.html", context)


# def edit (request, id):
#     book = get_object_or_404(Book, id=id)
#     if request.method == "POST":
#         book.name = request.POST.get("name")
#         book.author = request.POST.get("author")
#         book.no_pages = request.POST.get("pages")
#         book.price = request.POST.get("price")
#         book.cover = request.FILES.get("cover")
#         book.save()
#         return redirect(book.show_url)
#     return render(request, "books/editbook.html", {"book": book})


from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Book
from authors.models import Author
from .forms import BookForm


class BookListView(ListView):
    model = Book
    template_name = "books/home.html"
    context_object_name = "booklist"


class BookDetailView(DetailView):
    model = Book
    template_name = "books/bookdetail.html"
    context_object_name = "book"


class BookCreateView(CreateView):
    model = Book
    form_class = BookForm
    template_name = "books/createbook.html"
    success_url = reverse_lazy(
        "books:home"
    )  # Redirect to the book list after successful creation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["authors"] = Author.objects.all()
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        return response


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    template_name = "books/editbook.html"
    success_url = reverse_lazy("books:home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["authors"] = Author.objects.all()
        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["author"].queryset = Author.objects.all()
        return form


class BookDeleteView(DeleteView):
    model = Book
    template_name = "books/deletebook.html"
    success_url = reverse_lazy("books:home")

bookstore/books/templates/books/bookdetail.html
<!DOCTYPE html>
<html>
<head>
    <title>Book Detail</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}
</head>
<body>
    <div class="container">
        <h1 class="my-4">{{ book.name }}</h1>
        <div class="row">
            <div class="col-md-4">
                <img src="{{ book.image_url }}" alt="{{ book.name }}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <ul class="list-group">
                    <li class="list-group-item"><strong>ID:</strong> {{ book.id }}</li>
                    <li class="list-group-item"><strong>No. of Pages:</strong> {{ book.no_pages }}</li>
                    <li class="list-group-item"><strong>Author:</strong> {{ book.author }}</li>
                    <li class="list-group-item"><strong>Price:</strong> {{ book.price }}</li>
                </ul>
                <a href="{% url 'books:home' %}" class="btn btn-secondary mt-3">Back to List</a>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

bookstore/books/templates/books/createbook.html
{% extends "layouts/base.html" %}

{% block title %} Create Book {% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label for="name">Name</label>
        <input type="text" name="name" class="form-control" id="name" placeholder="Enter book name">
    </div>

    <div class="mb-3">
        <label for="pages">Number of Pages</label>
        <input type="number" name="pages" class="form-control" id="pages" placeholder="Enter number of pages">
    </div>

    <div class="mb-3">
        <label for="price">Price</label>
        <input type="number" name="price" class="form-control" id="price" placeholder="Enter price">
    </div>

    <div class="mb-3">
        <label for="author">Author</label>
        <select name="author" class="form-control" id="author" required>
            {% for author in authors %}
            <option value="{{ author.id }}">{{ author }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="mb-3">
        <label for="cover">Book Cover</label>
        <input type="file" name="cover" class="form-control" id="cover">
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

bookstore/books/templates/books/deletebook.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Delete Book</title>
    
  </head>

  
  <body>
    <div class="container">
      <h1>Delete Book</h1>
      <p>Are you sure you want to delete "{{ book.name }}"?</p>
      <form method="post" action="{% url 'books:deletebook' book.id %}">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
        <a href="{% url 'books:home' %}">Cancel</a>
      </form>
    </div>
  </body>
</html> 

bookstore/books/templates/books/editbook.html
{% extends "layouts/base.html" %}


{% block title %} Edit Book {% endblock %}

{% block content %}
<h1>Edit Book</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label for="name">Name</label>
        <input type="text" name="name" value="{{book.name}}" class="form-control" id="name" placeholder="Enter book name">
    </div>

    <div class="mb-3">
        <label for="pages">Number of Pages</label>
        <input type="number" name="pages" value="{{book.no_pages}}" class="form-control" id="pages" placeholder="Enter number of pages">
    </div>

    <div class="mb-3">
        <label for="price">Price</label>
        <input type="number" name="price" value="{{book.price}}" class="form-control" id="price" placeholder="Enter price">
    </div>

    <div class="mb-3">
        <label for="cover">book Cover</label>
        <input type="file" name="cover" class="form-control" id="cover">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>



</form>

{% endblock %}

bookstore/books/templates/books/home.html
{% extends "layouts/base.html" %}

{% block title %}Book List{% endblock %}

{% block content %}
    <h1>Book List</h1>
    <a href="{% url 'books:createbook' %}" class="btn btn-secondary my-4">Add Book</a>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Author</th>
                <th>Pages</th>
                <th>Price</th>
                <th>Cover</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for book in booklist %}
            <tr>
                <td>{{ book.id }}</td>
                <td><a href="{% url 'books:bookdetail' book.id %}">{{ book.name }}</a></td>
                <td>{{ book.author }}</td>
                <td>{{ book.pages }}</td>
                <td>{{ book.price }}</td>
                <td>
                    {% if book.cover %}
                    <img src="{{ book.cover.url }}" alt="{{ book.name }}" style="width: 100px;">
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'books:editbook' book.id %}" class="btn btn-primary">Edit</a>
                    <form action="{% url 'books:deletebook' book.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="7">No books available.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}